(async()=>{
 const P=PortalTools,$=P.element,E=P.escape,me=await P.start('clubs');if(!me)return;
 const call=(action,payload)=>P.result(sb.rpc('portal_club_action',{action,payload}));
 let memberships=[],tasks=[],ledger=[],contacts=[];
 const clubs=await P.result(sb.from('portal_clubs').select('id,name').eq('active',true).order('name'));
 const clubId=()=>$('clubChoice').value;
 const admin=()=>me.app_role==='system_admin'||memberships.some(m=>m.club_id===clubId()&&m.role==='club_admin'&&m.active);
 async function preferences(){memberships=await P.result(sb.from('portal_club_memberships').select('*').eq('person_id',me.person_id));const selected=new Set(memberships.filter(m=>m.role==='helper'&&m.active).map(m=>m.club_id));$('helperChoices').innerHTML=clubs.map(c=>`<p><label><input type="checkbox" value="${E(c.id)}" ${selected.has(c.id)?'checked':''}>${E(c.name)}</label></p>`).join('');
 const accessible=me.app_role==='system_admin'?clubs:clubs.filter(c=>memberships.some(m=>m.club_id===c.id&&m.active));const prev=clubId()||portalClubId;P.options($('clubChoice'),accessible);if(accessible.some(c=>c.id===prev))$('clubChoice').value=prev;
 const helper=await P.result(sb.rpc('has_active_person_role',{target_role:'hjelpetrener'}))||await P.result(sb.rpc('has_active_person_role',{target_role:'hjelpetreneraspirant'}));$('helperClubsForm').hidden=!(helper||me.app_role==='system_admin');}
 const states={open:'Åpent',assigned:'Tildelt',completed:'Fullført',cancelled:'Avlyst',registered:'Registrert',approved:'Godkjent',rejected:'Avvist',paid:'Utbetalt'};
 async function load(){const c=clubId();$('clubContent').hidden=!c;if(!c)return;
 contacts=await P.result(sb.rpc('portal_club_contacts',{c}));
 tasks=await P.result(sb.from('portal_club_tasks').select('*').eq('club_id',c).order('created_at',{ascending:false}));
 const isHelper=await P.result(sb.rpc('portal_helper_for',{c}));
 $('tasks').innerHTML=tasks.map(t=>`<article><h3>${E(t.title)}</h3><p>${E(t.description)}</p><p>${E(states[t.status])}</p>${t.status==='open'&&isHelper?`<button type="button" data-id="${E(t.id)}" data-action="accept_task">Ta oppdrag</button>`:''}${t.status==='assigned'&&(t.helper_id===me.person_id||admin())?`<button type="button" data-id="${E(t.id)}" data-action="complete_task">Marker fullført</button>`:''}${['open','assigned'].includes(t.status)&&(t.requester_id===me.person_id||admin())?`<button type="button" data-id="${E(t.id)}" data-action="cancel_task">Avlys oppdrag</button>`:''}</article>`).join('')||'<p>Ingen oppdrag.</p>';
 $('tasks').querySelectorAll('button').forEach(b=>P.action(b,'click',async()=>{await call(b.dataset.action,{id:b.dataset.id});await load();}));
 $('taskLink').innerHTML='<option value="">Frittstående registrering</option>'+tasks.filter(t=>t.helper_id===me.person_id&&['assigned','completed'].includes(t.status)).map(t=>`<option value="${E(t.id)}">${E(t.title)}</option>`).join('');
 ledger=await P.result(sb.from('portal_club_settlement').select('*').eq('club_id',c).order('occurred_on',{ascending:false}));
 $('ledger').innerHTML='<p>Sum (uten avviste): '+ledger.filter(l=>l.status!=='rejected').reduce((sum,l)=>sum+Number(l.amount),0).toLocaleString('nb-NO',{style:'currency',currency:'NOK'})+'</p>'+ledger.map(l=>`<article><h3>${E(l.description)}</h3><p>${E(l.occurred_on)} — ${E(l.amount)} kr — ${E(states[l.status])}</p>${admin()?`<p>Person: ${E(contacts.find(p=>p.id===l.person_id)?.full_name||l.person_id)}</p><label for="status-${E(l.source_table)}-${E(l.id)}">Oppgjørsstatus</label><select id="status-${E(l.source_table)}-${E(l.id)}">${['registered','approved','rejected','paid'].map(s=>`<option value="${s}" ${s===l.status?'selected':''}>${states[s]}</option>`).join('')}</select><button type="button" data-status="${E(l.id)}" data-source="${E(l.source_table)}">Lagre status for ${E(l.description)}</button>`:''}${(l.source_table==='portal_club_ledger'&&(admin()||(l.person_id===me.person_id&&l.status==='registered')))?`<label for="retry-${E(l.id)}">Kvittering for ${E(l.description)} (maks 25 MB)</label><input id="retry-${E(l.id)}" type="file"><button type="button" data-upload="${E(l.id)}">Last opp kvittering</button>`:''}${me.app_role==='system_admin'?`<button type="button" data-correct="${E(l.id)}" data-source="${E(l.source_table)}">Korriger beløp for ${E(l.description)}</button>`:''}${l.receipt_path?`<button type="button" data-receipt="${E(l.id)}" data-source="${E(l.source_table)}">Hent kvittering</button>`:''}</article>`).join('');
 $('ledger').querySelectorAll('[data-status]').forEach(b=>P.action(b,'click',async()=>{await P.result(sb.rpc('portal_set_settlement_status',{source_table:b.dataset.source,entry_id:b.dataset.status,new_status:$('status-'+b.dataset.source+'-'+b.dataset.status).value}));await load();}));
 $('ledger').querySelectorAll('[data-upload]').forEach(b=>P.action(b,'click',async()=>{const row=ledger.find(l=>l.id===b.dataset.upload),file=$('retry-'+row.id).files[0];if(!file)throw Error('Velg en fil først.');if(file.size>25*1024*1024)throw Error('Kvitteringen er større enn 25 MB.');if(row.receipt_path&&!confirm('Laste opp kvittering? En eksisterende kvittering for denne registreringen blir erstattet.'))return;await call('prepare_receipt',{id:row.id,name:file.name});await P.result(sb.storage.from('portal-club-receipts').upload(row.club_id+'/'+row.id,file,{upsert:true,contentType:file.type||'application/octet-stream'}));await load();}));
 $('ledger').querySelectorAll('[data-correct]').forEach(b=>P.action(b,'click',async()=>{const row=ledger.find(l=>l.id===b.dataset.correct&&l.source_table===b.dataset.source);$('correctionSource').value=row.source_table;$('correctionEntry').value=row.id;$('correctionAmount').value=row.amount;$('correctionReason').value='';$('correctionForm').hidden=false;$('correctionAmount').focus();}));
 $('ledger').querySelectorAll('[data-receipt]').forEach(b=>P.action(b,'click',async()=>{const row=ledger.find(l=>l.id===b.dataset.receipt&&l.source_table===b.dataset.source);const data=await P.result(sb.storage.from(row.receipt_bucket||'portal-club-receipts').createSignedUrl(row.receipt_path,60,{download:row.receipt_name}));$('receiptDownload').href=data.signedUrl;$('receiptDownload').hidden=false;$('receiptDownload').focus();}));
 $('ratesSection').hidden=!admin();const rates=await P.result(sb.from('portal_club_rates').select('*').eq('club_id',c).eq('year',Number($('rateYear').value)).maybeSingle());$('individualRate').value=rates?.individual_followup??0;$('dayRate').value=rates?.day_event??0;$('weekendRate').value=rates?.weekend_event??0;$('mileageRate').value=rates?.mileage_rate??0;
 const fee=await P.result(sb.from('portal_club_fees').select('amount').eq('club_id',c).eq('year',Number($('rateYear').value)).maybeSingle());$('membershipFee').value=fee?.amount??'';
 $('legacyOslo').hidden=false;
 }
 function entryFields(){const work=$('entryKind').value==='work';const custom=!work||$('activityType').value==='other';$('workFields').hidden=!work;$('entryAmount').hidden=!custom;$('amountLabel').hidden=!custom;$('entryAmount').required=custom;}
 $('entryKind').addEventListener('change',entryFields);$('activityType').addEventListener('change',entryFields);entryFields();
 populateDateSelects('entry');const year=new Date().getFullYear();$('rateYear').innerHTML=Array.from({length:7},(_,n)=>`<option value="${year-1+n}">${year-1+n}</option>`).join('');$('rateYear').value=String(year);
 P.action($('helperClubsForm'),'submit',async()=>{await P.result(sb.rpc('portal_set_helper_clubs',{club_ids:[...$('helperChoices').querySelectorAll('input:checked')].map(n=>n.value)}));await preferences();await load();});
 P.action($('clubChoice'),'change',async()=>{if(clubId()&&clubId()!==portalClubId){localStorage.setItem('portalClubId',clubId());location.reload();return;}await load();});P.action($('rateYear'),'change',load);
 P.action($('taskForm'),'submit',async()=>{await call('create_task',{club_id:clubId(),title:$('taskTitle').value,description:$('taskDescription').value});$('taskForm').reset();await load();});
 P.action($('ledgerForm'),'submit',async()=>{const date=getDateFromSelects('entry');if(!date)throw Error('Velg en gyldig dato.');const file=$('receiptFile').files[0];if(file&&file.size>25*1024*1024)throw Error('Kvitteringen er større enn 25 MB.');const c=clubId();const r=await call('register_ledger',{club_id:c,task_id:$('taskLink').value||null,kind:$('entryKind').value,occurred_on:date,description:$('entryDescription').value,amount:$('entryAmount').value,activity_type:$('activityType').value,kilometers:$('kilometers').value,receipt_name:file?.name||null});
 $('ledgerForm').reset();populateDateSelects('entry');entryFields();
 if(file){try{await P.result(sb.storage.from('portal-club-receipts').upload(c+'/'+r.id,file,{upsert:false,contentType:file.type||'application/octet-stream'}));}catch(e){await load();throw Error('Registreringen er lagret, men kvitteringen kunne ikke lastes opp. Bruk Last opp kvittering ved den lagrede registreringen for å prøve igjen. '+e.message);}}
 await load();});
 P.action($('correctionForm'),'submit',async()=>{await P.result(sb.rpc('portal_correct_settlement',{source_table:$('correctionSource').value,entry_id:$('correctionEntry').value,new_amount:Number($('correctionAmount').value),reason:$('correctionReason').value}));$('correctionForm').hidden=true;await load();});
 P.action($('ratesForm'),'submit',async()=>{await call('save_rates',{club_id:clubId(),year:$('rateYear').value,individual_followup:$('individualRate').value,day_event:$('dayRate').value,weekend_event:$('weekendRate').value,mileage_rate:$('mileageRate').value});await load();});
 P.action($('membershipFeeForm'),'submit',async()=>{await P.result(sb.from('portal_club_fees').upsert({club_id:clubId(),year:Number($('rateYear').value),amount:Number($('membershipFee').value)}));await load();});
 $('exportLedger').onclick=()=>{const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const rows=[['Klubb','Person','Dato','Type','Beskrivelse','Beløp','Status'],...ledger.map(l=>[clubs.find(c=>c.id===l.club_id)?.name,contacts.find(p=>p.id===l.person_id)?.full_name||l.person_id,l.occurred_on,l.kind,l.description,l.amount,states[l.status]])];downloadBlob('oppgjor-'+clubId()+'.csv','\ufeff'+rows.map(r=>r.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8');};
 await preferences();await load();P.status('Velg klubb. Oppdrag og oppgjør holdes adskilt per klubb.');
})().catch(e=>PortalTools.status(e.message));
