(async()=>{
 const P=PortalTools,$=P.element,E=P.escape;const me=await P.start('my-dog');if(!me)return;
 const dogs=await P.result(sb.from('dogs').select('id,name,chip_number,birth_date,notes').order('name'));
 const permitted=[];for(const dog of dogs){if(await P.result(sb.rpc('portal_can_dog',{d:dog.id})))permitted.push(dog);}
 P.options($('dogChoice'),permitted);const clinics=await P.result(sb.from('portal_clinics').select('id,name').eq('active',true).order('name'));P.options($('clinicChoice'),clinics);$('clinicChoice').options[0].textContent='Ingen klinikk';
 populateDateSelects('birth');$('birthYear').innerHTML=Array.from({length:41},(_,n)=>{const y=new Date().getFullYear()-n;return `<option value="${y}">${y}</option>`;}).join('');
 $('birthdayEnabled').onchange=()=>{$('birthdayFields').hidden=!$('birthdayEnabled').checked;};
 const dogId=()=>$('dogChoice').value;
 async function records(){const rs=await P.result(sb.from('portal_dog_records').select('*').eq('dog_id',dogId()).order('created_at'));$('records').innerHTML=rs.map(r=>`<article><h3>${E(r.title)}</h3><p style="white-space:pre-wrap">${E(r.body)}</p><button type="button" data-edit="${E(r.id)}">Endre ${E(r.title)}</button><button type="button" data-delete="${E(r.id)}">Slett ${E(r.title)}</button></article>`).join('')||'<p>Ingen registrerte opplysninger.</p>';
 $('records').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const r=rs.find(r=>r.id===b.dataset.edit);$('recordId').value=r.id;$('recordTitle').value=r.title;$('recordBody').value=r.body;$('recordTitle').focus();});
 $('records').querySelectorAll('[data-delete]').forEach(b=>P.action(b,'click',async()=>{if(!confirm('Slette denne opplysningen? Slettingen logges.'))return;await P.result(sb.from('portal_dog_records').delete().eq('id',b.dataset.delete).eq('dog_id',dogId()));await records();}));
 }
 async function docs(){const ds=await P.result(sb.from('portal_dog_documents').select('*').eq('dog_id',dogId()).order('created_at'));$('documents').innerHTML=ds.map(d=>`<p>${E(d.name)} <button type="button" data-download="${E(d.id)}">Hent nedlastingslenke for ${E(d.name)}</button> <button type="button" data-remove="${E(d.id)}">Slett dokumentet ${E(d.name)}</button></p>`).join('')||'<p>Ingen dokumenter.</p>';
 $('documents').querySelectorAll('[data-download]').forEach(b=>P.action(b,'click',async()=>{const d=ds.find(d=>d.id===b.dataset.download);const url=await P.result(sb.storage.from('portal-dog-documents').createSignedUrl(d.storage_path,60,{download:d.name}));$('downloadLink').href=url.signedUrl;$('downloadLink').textContent='Last ned '+d.name;$('downloadLink').hidden=false;$('downloadLink').focus();}));
 $('documents').querySelectorAll('[data-remove]').forEach(b=>P.action(b,'click',async()=>{const d=ds.find(d=>d.id===b.dataset.remove);if(!confirm('Slette dokumentet '+d.name+'?'))return;await P.result(sb.storage.from('portal-dog-documents').remove([d.storage_path]));await P.result(sb.from('portal_dog_documents').delete().eq('id',d.id));$('downloadLink').hidden=true;await docs();}));}

 P.action($('dogChoice'),'change',async()=>{const dog=permitted.find(d=>d.id===dogId());$('dogContent').hidden=!dog;if(!dog)return;
 $('profileForm').reset();$('recordForm').reset();$('recordId').value='';$('downloadLink').hidden=true;
 $('dogName').value=dog.name;$('dogChip').value=dog.chip_number||'';$('dogNotes').value=dog.notes||'';$('birthdayEnabled').checked=!!dog.birth_date;$('birthdayFields').hidden=!dog.birth_date;if(dog.birth_date)setDateSelects('birth',dog.birth_date);
 const owner=await P.result(sb.rpc('portal_owns_dog',{d:dog.id}));$('clinicForm').hidden=!(owner||me.app_role==='system_admin');const link=await P.result(sb.from('portal_dog_clinics').select('clinic_id').eq('dog_id',dog.id).maybeSingle());$('clinicChoice').value=link?.clinic_id||'';await records();await docs();});
 P.action($('profileForm'),'submit',async()=>{const date=$('birthdayEnabled').checked?getDateFromSelects('birth'):null;if($('birthdayEnabled').checked&&!date)throw Error('Velg en gyldig fødselsdato.');await P.result(sb.rpc('portal_save_dog',{d:dogId(),dog_name:$('dogName').value,chip:$('dogChip').value,birthday:date,dog_notes:$('dogNotes').value}));Object.assign(permitted.find(d=>d.id===dogId()),{name:$('dogName').value,chip_number:$('dogChip').value,birth_date:date,notes:$('dogNotes').value});});
 P.action($('clinicForm'),'submit',async()=>{const c=$('clinicChoice').value;if(c)await P.result(sb.from('portal_dog_clinics').upsert({dog_id:dogId(),clinic_id:c,updated_at:new Date().toISOString()}));else await P.result(sb.from('portal_dog_clinics').delete().eq('dog_id',dogId()));});
 P.action($('recordForm'),'submit',async()=>{const r={dog_id:dogId(),title:$('recordTitle').value.trim(),body:$('recordBody').value,updated_at:new Date().toISOString()};if($('recordId').value)await P.result(sb.from('portal_dog_records').update(r).eq('id',$('recordId').value).eq('dog_id',dogId()));else await P.result(sb.from('portal_dog_records').insert(r));$('recordForm').reset();$('recordId').value='';await records();});
 $('newRecord').onclick=()=>{$('recordForm').reset();$('recordId').value='';$('recordTitle').focus();};
 P.action($('uploadForm'),'submit',async()=>{const file=$('dogFile').files[0];if(!file||file.size>25*1024*1024)throw Error('Velg et dokument på maks 25 MB.');const id=crypto.randomUUID(),path=dogId()+'/'+id;await P.result(sb.from('portal_dog_documents').insert({id,dog_id:dogId(),name:file.name,storage_path:path}));try{await P.result(sb.storage.from('portal-dog-documents').upload(path,file,{upsert:false,contentType:file.type||'application/octet-stream'}));}catch(e){await sb.from('portal_dog_documents').delete().eq('id',id);throw e;}$('uploadForm').reset();await docs();});
 P.status(permitted.length?'Velg hund for å åpne opplysningene.':'Ingen hunder er knyttet til din tilgang. Kontakt systemadministrator.');
})().catch(e=>PortalTools.status(e.message));
