(async()=>{
 const P=PortalTools,$=P.element,E=P.escape,me=await P.start('portal-support');if(!me)return;if(me.app_role!=='system_admin')throw Error('Bare systemadministrator har tilgang.');$('supportContent').hidden=false;
 let people=[],clubs=[],clinics=[];
 async function load(){people=await P.result(sb.from('portal_person_identities').select('id,full_name').order('full_name'));clubs=await P.result(sb.from('portal_clubs').select('*').order('name'));clinics=await P.result(sb.from('portal_clinics').select('*').order('name'));P.options($('personChoice'),people,'full_name');P.options($('supportClub'),clubs);P.options($('supportClinic'),clinics);
 P.options($('newDogOwner'),people,'full_name');P.options($('dogPerson'),people,'full_name');
 const dogs=await P.result(sb.from('dogs').select('id,name').order('name'));P.options($('supportDog'),dogs);
 const organisations=[...clubs.map(r=>({...r,table:'portal_clubs',kind:'Klubb'})),...clinics.map(r=>({...r,table:'portal_clinics',kind:'Klinikk'}))];
 $('organisationSettings').innerHTML=organisations.map((r,i)=>`<form data-organisation="${i}"><h3>${E(r.kind)}: ${E(r.name)}</h3><label for="orgName-${i}">Navn</label><input id="orgName-${i}" value="${E(r.name)}" required><label><input id="orgActive-${i}" type="checkbox" ${r.active?'checked':''}> Aktiv</label><button type="submit">Lagre ${E(r.name)}</button></form>`).join('');
 $('organisationSettings').querySelectorAll('form').forEach(f=>P.action(f,'submit',async()=>{const i=Number(f.dataset.organisation),r=organisations[i];await P.result(sb.from(r.table).update({name:$('orgName-'+i).value.trim(),active:$('orgActive-'+i).checked}).eq('id',r.id));await load();}));
 const links=await P.result(sb.from('dog_person_links').select('id,dog_id,person_id,relation_type').eq('active',true));const assignments=await P.result(sb.from('dog_professional_assignments').select('id,dog_id,professional_person_id').eq('active',true).eq('assignment_role','skoletrener'));
 const dogLinks=[...links.map(r=>({...r,action:'revoke_handler',label:r.relation_type})),...assignments.map(r=>({...r,person_id:r.professional_person_id,action:'revoke_school',label:'Skoletrener'}))];
 $('dogAccessList').innerHTML=dogLinks.map((r,i)=>`<p>${E(dogs.find(d=>d.id===r.dog_id)?.name||r.dog_id)} — ${E(people.find(p=>p.id===r.person_id)?.full_name||r.person_id)} — ${E(r.label)} <button type="button" data-doglink="${i}">Trekk tilbake tilknytningen</button></p>`).join('');
 $('dogAccessList').querySelectorAll('button').forEach(b=>P.action(b,'click',async()=>{const r=dogLinks[Number(b.dataset.doglink)];if(!confirm('Trekke tilbake denne hundetilknytningen?'))return;await P.result(sb.rpc('portal_support_dog',{action:r.action,payload:{id:r.id}}));await load();}));
 const audit=await P.result(sb.from('portal_access_audit').select('happened_at,actor_user_id,entity,operation').order('id',{ascending:false}).limit(50));$('auditList').innerHTML=audit.map(r=>`<p>${E(new Date(r.happened_at).toLocaleString('nb-NO'))} — ${E(r.entity)} — ${E(r.operation)} — ${E(r.actor_user_id||'System')}</p>`).join('');

 const staff=await P.result(sb.from('portal_staff_access').select('*').eq('active',true));const members=await P.result(sb.from('portal_club_memberships').select('*').eq('active',true));
 const labels={nav:'NAV',veterinarian:'Veterinær',club_admin:'Klubbadministrator',member:'Medlem',helper:'Hjelpetrener'};
 $('accessList').innerHTML=[...staff.map(r=>({...r,table:'portal_staff_access'})),...members.map(r=>({...r,table:'portal_club_memberships'}))].map((r,i)=>`<p>${E(people.find(p=>p.id===r.person_id)?.full_name||r.person_id)} — ${E(r.role==='member'?(r.membership_kind==='secondary'?'Sekundært medlem':'Primært medlem'):labels[r.role])} — ${E(clubs.find(c=>c.id===r.club_id)?.name||clinics.find(c=>c.id===r.clinic_id)?.name||'Alle hunder')} <button type="button" data-index="${i}">Trekk tilbake denne tilgangen</button></p>`).join('');
 const rows=[...staff.map(r=>({...r,table:'portal_staff_access'})),...members.map(r=>({...r,table:'portal_club_memberships'}))];$('accessList').querySelectorAll('button').forEach(b=>P.action(b,'click',async()=>{const r=rows[Number(b.dataset.index)];if(!confirm('Trekke tilbake tilgangen?'))return;let q=sb.from(r.table).update({active:false});if(r.id)q=q.eq('id',r.id);else q=q.eq('club_id',r.club_id).eq('person_id',r.person_id).eq('role',r.role);await P.result(q);await load();}));}
 P.action($('clubForm'),'submit',async()=>{await P.result(sb.from('portal_clubs').insert({name:$('clubName').value.trim(),active:true}));$('clubForm').reset();await load();});
 P.action($('clinicCreateForm'),'submit',async()=>{await P.result(sb.from('portal_clinics').insert({name:$('clinicName').value.trim(),active:true}));$('clinicCreateForm').reset();await load();});
 P.action($('accessForm'),'submit',async()=>{const role=$('accessRole').value,person_id=$('personChoice').value;if(!person_id)throw Error('Velg person.');if(['primary','secondary'].includes(role)){if(!$('supportClub').value)throw Error('Velg klubb.');await P.result(sb.rpc('portal_set_membership',{p:person_id,c:$('supportClub').value,kind:role}));}else if(['nav','veterinarian'].includes(role)){const clinic_id=role==='veterinarian'?$('supportClinic').value:null;if(role==='veterinarian'&&!clinic_id)throw Error('Velg klinikk.');let q=sb.from('portal_staff_access').select('id').eq('person_id',person_id).eq('role',role);q=clinic_id?q.eq('clinic_id',clinic_id):q.is('clinic_id',null);const old=await P.result(q.maybeSingle());if(old)await P.result(sb.from('portal_staff_access').update({active:true}).eq('id',old.id));else await P.result(sb.from('portal_staff_access').insert({person_id,role,clinic_id}));}else{const club_id=$('supportClub').value;if(!club_id)throw Error('Velg klubb.');await P.result(sb.from('portal_club_memberships').upsert({club_id,person_id,role,active:true}));}await load();});
 P.action($('createDogForm'),'submit',async()=>{await P.result(sb.rpc('portal_support_dog',{action:'create',payload:{name:$('newDogName').value,person_id:$('newDogOwner').value}}));$('createDogForm').reset();await load();});
 P.action($('dogAccessForm'),'submit',async()=>{await P.result(sb.rpc('portal_support_dog',{action:$('dogAccessKind').value,payload:{dog_id:$('supportDog').value,person_id:$('dogPerson').value,club_id:$('supportClub').value||portalClubId}}));await load();});
 await load();P.status('Supporttilgang er aktiv.');
})().catch(e=>PortalTools.status(e.message));
