// Run against an isolated PGlite instance. Never uses the production database.
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
(async()=>{const db=new PGlite();await db.exec(fs.readFileSync(path.join(__dirname,'access-baseline.sql'),'utf8'));
for(const file of fs.readdirSync(path.join(root,'supabase/migrations')).sort())await db.exec(fs.readFileSync(path.join(root,'supabase/migrations',file),'utf8'));
const id=(n)=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
for(let n=1;n<=5;n++){await db.query('insert into auth.users values($1)',[id(n)]);await db.query('insert into persons values($1,$2)',[id(n),'TEST '+n]);await db.query('insert into app_users values($1,$1,$2,true)',[id(n),n===4?'system_admin':'readonly']);}
for(let n=10;n<=11;n++)await db.query('insert into dogs(id,name) values($1,$2)',[id(n),'Dog '+n]);
await db.query('insert into dog_person_links(dog_id,person_id) values($1,$2)',[id(10),id(1)]);
for(let n=20;n<=21;n++)await db.query('insert into portal_clinics(id,name) values($1,$2)',[id(n),'Clinic '+n]);
await db.query('insert into portal_dog_clinics values($1,$2,now()),($3,$4,now())',[id(10),id(20),id(11),id(21)]);
await db.query("insert into portal_staff_access(person_id,role,clinic_id) values($1,'veterinarian',$2),($3,'nav',null)",[id(2),id(20),id(3)]);
async function as(n){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);await db.exec('set role authenticated');}
async function allowed(d){return (await db.query('select portal_can_dog($1) ok',[id(d)])).rows[0].ok;}
async function deny(sql,params){await assert.rejects(db.query(sql,params),e=>e.code==='42501');}
await as(2);assert(await allowed(10));assert(!await allowed(11));
await deny('insert into portal_dog_records(dog_id,title) values($1,$2)',[id(11),'Forbidden']);
await deny("insert into portal_staff_access(person_id,role) values($1,'nav')",[id(2)]);
await db.query('insert into portal_dog_records(id,dog_id,title) values($1,$2,$3)',[id(30),id(10),'Record']);
await db.query('update portal_dog_records set body=$1 where id=$2',['edited',id(30)]);
assert.equal((await db.query('select body from portal_dog_records where id=$1',[id(30)])).rows[0].body,'edited');
await db.query('delete from portal_dog_records where id=$1',[id(30)]);
await db.query('insert into portal_dog_documents(id,dog_id,name,storage_path) values($1,$2,$3,$4)',[id(40),id(10),'Document',id(10)+'/'+id(40)]);
await db.query("insert into storage.objects(bucket_id,name) values('portal-dog-documents',$1)",[id(10)+'/'+id(40)]);
await deny("insert into storage.objects(bucket_id,name) values('portal-dog-documents',$1)",[id(11)+'/'+id(40)]);
await as(2);await deny('select portal_save_dog($1,$2,null,null,$3)',[id(11),'Forbidden','No']);assert.equal((await db.query('update portal_dog_clinics set clinic_id=$1 where dog_id=$2 returning dog_id',[id(20),id(11)])).rows.length,0);
await as(3);assert(await allowed(10));assert(await allowed(11));await db.query('select portal_save_dog($1,$2,null,null,$3)',[id(11),'Updated','Note']);
assert.equal((await db.query("select * from storage.objects where bucket_id='portal-dog-documents'")).rows.length,1);
await as(1);await db.query('update portal_dog_clinics set clinic_id=$1 where dog_id=$2',[id(21),id(10)]);
await as(2);assert(!await allowed(10));assert.equal((await db.query("select * from storage.objects where bucket_id='portal-dog-documents'")).rows.length,0);
await as(5);assert(!await allowed(10));assert(!await allowed(11));
await as(4);assert(await allowed(10));assert(await allowed(11));assert((await db.query("select * from portal_access_audit where operation='DELETE'")).rows.length>0);
await deny('delete from portal_access_audit',[]);
await db.exec('reset role');
await db.query("insert into roles values($1,'hjelpetrener')",[id(80)]);
await db.query('insert into person_roles values($1,$2,true,null,null)',[id(1),id(80)]);
await db.query("insert into portal_clubs(id,name,active) values($1,'Club A',true),($2,'Club B',true)",[id(60),id(61)]);
await db.query("insert into portal_club_memberships values($1,$2,'club_admin',true),($3,$4,'club_admin',true)",[id(60),id(2),id(61),id(5)]);
await as(1);await db.query('select portal_set_helper_clubs($1)',[[id(60),id(61)]]);
assert.equal((await db.query("select * from portal_club_memberships where role='helper' and active")).rows.length,2);
const call=async(action,payload)=>(await db.query('select portal_club_action($1,$2) result',[action,JSON.stringify(payload)])).rows[0].result;
const task=(await call('create_task',{club_id:id(60),title:'TEST request'})).id;
await call('accept_task',{id:task});await call('complete_task',{id:task});
await assert.rejects(call('register_ledger',{club_id:id(61),task_id:task,kind:'expense',occurred_on:'2026-09-24',description:'Wrong club',amount:1}));
const entry=(await call('register_ledger',{club_id:id(60),task_id:task,kind:'expense',occurred_on:'2026-09-24',description:'Receipt A',amount:100,receipt_name:'test.pdf'})).id;
await db.query("insert into storage.objects(bucket_id,name) values('portal-club-receipts',$1)",[id(60)+'/'+entry]);
await as(5);assert.equal((await db.query('select * from portal_club_ledger where id=$1',[entry])).rows.length,0);
await assert.rejects(call('ledger_status',{id:entry,status:'paid'}),e=>e.code==='42501');
assert.equal((await db.query("select * from storage.objects where bucket_id='portal-club-receipts'")).rows.length,0);
await as(2);assert.equal((await db.query('select * from portal_club_ledger where id=$1',[entry])).rows.length,1);
await assert.rejects(call('ledger_status',{id:entry,status:'paid'}));await call('ledger_status',{id:entry,status:'approved'});await call('ledger_status',{id:entry,status:'paid'});
await call('save_rates',{club_id:id(60),year:2026,individual_followup:400,day_event:800,weekend_event:1600,mileage_rate:3.5});
await as(1);const work=(await call('register_ledger',{club_id:id(60),kind:'work',activity_type:'day_event',kilometers:10,occurred_on:'2026-09-24',description:'Fixed rate',amount:999999})).id;
assert.equal(Number((await db.query('select amount from portal_club_ledger where id=$1',[work])).rows[0].amount),835);
await as(2);await call('save_rates',{club_id:id(60),year:2026,individual_followup:500,day_event:900,weekend_event:1700,mileage_rate:4});
assert.equal(Number((await db.query('select amount from portal_club_ledger where id=$1',[work])).rows[0].amount),835);
await as(5);await assert.rejects(call('prepare_receipt',{id:work,name:'forbidden.pdf'}),e=>e.code==='42501');
await as(1);await call('prepare_receipt',{id:work,name:'retry.pdf'});
await db.query("insert into storage.objects(bucket_id,name) values('portal-club-receipts',$1)",[id(60)+'/'+work]);
await assert.rejects(call('register_ledger',{club_id:id(60),kind:'work',activity_type:'day_event',occurred_on:'2027-09-24',description:'Missing rate',amount:1}));
console.log('PASS: fixed honorarium plus mileage calculated server-side; submitted amount ignored for standard rates; historical amounts remain fixed; receipt retries preserve ledger ID.');
await as(1);await db.query('select portal_set_helper_clubs($1)',[[]]);assert.equal((await db.query('select * from portal_club_ledger where id=$1',[entry])).rows.length,1);
assert.equal((await db.query('select portal_helper_for($1) ok',[id(60)])).rows[0].ok,false);
await deny("insert into portal_club_memberships values($1,$2,'club_admin',true)",[id(60),id(1)]);
await as(3);await deny("select portal_support_dog('create',$1)",[JSON.stringify({person_id:id(3),name:'Forbidden'})]);
await as(4);const supportDog=(await db.query("select portal_support_dog('create',$1) id",[JSON.stringify({person_id:id(1),name:'Support created'})])).rows[0].id;
await db.query("select portal_support_dog('link_school',$1)",[JSON.stringify({dog_id:supportDog,person_id:id(5)})]);
const assignment=(await db.query('select id from dog_professional_assignments where dog_id=$1',[supportDog])).rows[0].id;
await as(5);assert.equal((await db.query('select portal_can_dog($1) ok',[supportDog])).rows[0].ok,true);assert(!await allowed(10));
await as(4);await db.query("select portal_support_dog('revoke_school',$1)",[JSON.stringify({id:assignment})]);
await as(5);assert.equal((await db.query('select portal_can_dog($1) ok',[supportDog])).rows[0].ok,false);
console.log('PASS: support creates dog with owner, assigns and revokes school trainer; NAV cannot grant ownership or create dogs.');
await db.exec('reset role');
await db.query("insert into guideview_sessions(id,dog_id,created_by,club_id) values($1,$2,$3,$4),($5,$2,$3,$6)",[id(90),id(10),id(1),id(60),id(91),id(61)]);
await db.query("insert into portal_club_memberships values($1,$2,'member',true)",[id(60),id(1)]);
await as(2);assert.equal((await db.query('select portal_gv_is_admin(null,$1) ok',[id(90)])).rows[0].ok,true);
assert.equal((await db.query('select portal_gv_is_admin($1,$2) ok',[id(60),id(91)])).rows[0].ok,false);
assert.equal((await db.query("select portal_gv_can_create($1,$2,$3,'follow_up') ok",[id(10),id(60),id(1)])).rows[0].ok,true);
assert.equal((await db.query("select portal_gv_can_create($1,$2,$3,'follow_up') ok",[id(10),id(61),id(1)])).rows[0].ok,false);
await as(3);assert.equal((await db.query('select portal_gv_is_admin(null,$1) ok',[id(90)])).rows[0].ok,false);
assert.equal((await db.query("select portal_gv_can_create($1,$2,$3,'follow_up') ok",[id(10),id(60),id(1)])).rows[0].ok,false);
await as(4);assert.equal((await db.query('select portal_gv_is_admin(null,$1) ok',[id(91)])).rows[0].ok,true);
console.log('PASS: GuideView administration follows session club; spoofing club input does not grant access; NAV dog access gives no GuideView administration.');
console.log('PASS: club selection, task status flow, task-owned payer, cross-club ledger/receipt isolation, approval-before-payment, history after leaving and no self-admin.');
console.log('PASS: isolated PostgreSQL RLS tests: clinic boundary, NAV, owner clinic change, revocation, upload/read isolation, CRUD, support, audit and no privilege escalation.');await db.close();})().catch(e=>{console.error(e.message,e.code);process.exitCode=1});
