import { createClient, servePortal } from "../_shared/portal-scope.ts";
const U=Deno.env.get("SUPABASE_URL")||"", S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default||"", P=JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")||"{}").default||Deno.env.get("SUPABASE_ANON_KEY")||"";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-portal-club","Access-Control-Allow-Methods":"POST,OPTIONS"};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...H,"Content-Type":"application/json"}});
async function C(req:Request){const a=req.headers.get("Authorization")||"";if(!a.startsWith("Bearer "))throw Error("AUTH");const u=createClient(U,P,{global:{headers:{Authorization:a}},auth:{persistSession:false}}),d=createClient(U,S,{auth:{persistSession:false}});const {data:{user}}=await u.auth.getUser();if(!user)throw Error("AUTH");const {data:p}=await d.from("app_users").select("person_id,app_role,active").eq("user_id",user.id).maybeSingle();if(!p?.active||!p.person_id)throw Error("NO_PERSON");return{d,pid:p.person_id,role:p.app_role}}
// A missing deadline keeps the form open; invalid stored dates fail closed.
function deadlinePassed(form: {closes_at?: string | null}, now = Date.now()) {
  if (!form.closes_at) return false;
  const deadline = Date.parse(form.closes_at);
  return !Number.isFinite(deadline) || now >= deadline;
}
const A=(r:string)=>["admin","system_admin"].includes(r);
async function def(d:any,id:string){const q=await d.from("form_questions").select("*").eq("form_id",id).order("position");if(q.error)throw q.error;const ids=(q.data||[]).map((x:any)=>x.id);let o:any[]=[];if(ids.length){const z=await d.from("form_question_options").select("*").in("question_id",ids).order("position");if(z.error)throw z.error;o=z.data||[]}return{questions:q.data||[],options:o}}
servePortal(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});try{const {d,pid,role}=await C(req),b=await req.json(),a=String(b.action||"");
 if(a==="admin_list"){if(!A(role))return J({error:"Kun administrator."},403);const r=await d.from("forms").select("*").order("created_at",{ascending:false});return r.error?J({error:r.error.message},400):J({forms:r.data||[]})}
 if(a==="people"){if(!A(role))return J({error:"Kun administrator."},403);const r=await d.from("persons").select("id,full_name,email,membership_status").order("full_name");return r.error?J({error:r.error.message},400):J({people:r.data||[]})}
 if(a==="create"){if(!A(role))return J({error:"Kun administrator."},403);if(b.closesAt && (typeof b.closesAt!=="string" || !Number.isFinite(Date.parse(b.closesAt))))return J({error:"Ugyldig svarfrist."},400);const r=await d.from("forms").insert({title:String(b.title||"").trim(),description:String(b.description||"").trim()||null,response_mode:b.responseMode==="anonymous"?"anonymous":"identified",closes_at:b.closesAt||null,created_by_person_id:pid}).select("*").single();return r.error?J({error:r.error.message},400):J({form:r.data})}
 if(a==="get_admin"){if(!A(role))return J({error:"Kun administrator."},403);const id=String(b.formId),f=await d.from("forms").select("*").eq("id",id).single(),x=await def(d,id),rr=await d.from("form_recipients").select("person_id").eq("form_id",id),rs=await d.from("form_responses").select("id,person_id,submitted_at").eq("form_id",id);return J({form:f.data,...x,recipients:rr.data||[],responses:rs.data||[]})}
 if(a==="add_question"){if(!A(role))return J({error:"Kun administrator."},403);const id=String(b.formId),last=await d.from("form_questions").select("position").eq("form_id",id).order("position",{ascending:false}).limit(1),q=await d.from("form_questions").insert({form_id:id,position:(last.data?.[0]?.position??-1)+1,question_text:String(b.questionText||"").trim(),help_text:String(b.helpText||"").trim()||null,question_type:b.questionType,required:!!b.required,scale_min:b.questionType==="scale"?Number(b.scaleMin||1):null,scale_max:b.questionType==="scale"?Number(b.scaleMax||5):null}).select("*").single();if(q.error)return J({error:q.error.message},400);const os=(b.options||[]).map((x:any)=>String(x).trim()).filter(Boolean);if(os.length){const z=await d.from("form_question_options").insert(os.map((x:string,i:number)=>({question_id:q.data.id,position:i,option_text:x})));if(z.error)return J({error:z.error.message},400)}return J({success:true})}
 if(a==="delete_question"){if(!A(role))return J({error:"Kun administrator."},403);const r=await d.from("form_questions").delete().eq("id",String(b.questionId));return r.error?J({error:r.error.message},400):J({success:true})}
 if(a==="set_recipients"){if(!A(role))return J({error:"Kun administrator."},403);const id=String(b.formId),ids=[...new Set((b.personIds||[]).map(String))];let r=await d.from("form_recipients").delete().eq("form_id",id);if(r.error)return J({error:r.error.message},400);if(ids.length){r=await d.from("form_recipients").insert(ids.map((person_id:any)=>({form_id:id,person_id})));if(r.error)return J({error:r.error.message},400)}return J({success:true,count:ids.length})}
 if(a==="set_status"){if(!A(role))return J({error:"Kun administrator."},403);const r=await d.from("forms").update({status:b.status,updated_at:new Date().toISOString()}).eq("id",String(b.formId));return r.error?J({error:r.error.message},400):J({success:true})}
 if(a==="my_forms"){const rr=await d.from("form_recipients").select("form_id").eq("person_id",pid),ids=(rr.data||[]).map((x:any)=>x.form_id);if(!ids.length)return J({forms:[]});const f=await d.from("forms").select("*").in("id",ids).eq("status","published").order("created_at",{ascending:false}),done=await d.from("form_responses").select("form_id").eq("person_id",pid).in("form_id",ids),ds=new Set((done.data||[]).map((x:any)=>x.form_id));return J({forms:(f.data||[]).filter((x:any)=>!deadlinePassed(x)).map((x:any)=>({...x,completed:ds.has(x.id)}))})}
 if(a==="get_public"){const id=String(b.formId),f=await d.from("forms").select("*").eq("id",id).single(),r=await d.from("form_recipients").select("id").eq("form_id",id).eq("person_id",pid).maybeSingle();if(!r.data||f.data?.status!=="published")return J({error:"Skjemaet er ikke tilgjengelig."},403);if(deadlinePassed(f.data))return J({error:"Svarfristen er utløpt."},403);return J({form:f.data,...await def(d,id)})}
 if(a==="submit"){const id=String(b.formId),f=await d.from("forms").select("*").eq("id",id).single(),r=await d.from("form_recipients").select("id").eq("form_id",id).eq("person_id",pid).maybeSingle();if(!r.data||f.data?.status!=="published")return J({error:"Skjemaet er ikke tilgjengelig."},403);if(deadlinePassed(f.data))return J({error:"Svarfristen er utløpt."},403);const x=await def(d,id),ans=b.answers||{};for(const q of x.questions)if(q.required&&(ans[q.id]===undefined||ans[q.id]===""||(Array.isArray(ans[q.id])&&!ans[q.id].length)))return J({error:"Obligatorisk spørsmål mangler: "+q.question_text},400);const person=f.data.response_mode==="anonymous"?null:pid;if(person){const old=await d.from("form_responses").select("id").eq("form_id",id).eq("person_id",pid).maybeSingle();if(old.data)return J({error:"Du har allerede svart."},409)}const rs=await d.from("form_responses").insert({form_id:id,person_id:person}).select("id").single();if(rs.error)return J({error:rs.error.message},400);const rows=x.questions.filter((q:any)=>ans[q.id]!==undefined).map((q:any)=>({response_id:rs.data.id,question_id:q.id,answer_json:ans[q.id]}));if(rows.length){const z=await d.from("form_answers").insert(rows);if(z.error)return J({error:z.error.message},400)}return J({success:true})}
 if(a==="results"){if(!A(role))return J({error:"Kun administrator."},403);const id=String(b.formId),x=await def(d,id),rs=await d.from("form_responses").select("*").eq("form_id",id),ids=(rs.data||[]).map((x:any)=>x.id);let an:any[]=[];if(ids.length){const z=await d.from("form_answers").select("*").in("response_id",ids);an=z.data||[]}return J({...x,responses:rs.data||[],answers:an})}
 return J({error:"Ugyldig handling."},400)
}catch(e){console.error("[forms-actions]",e);return J({error:e instanceof Error?e.message:String(e)},500)}});