-- Every pre-existing row belongs to Oslo, confirmed by the system owner.
begin;
create function public.portal_current_club() returns uuid language plpgsql stable as $$
declare h text;
begin
 h:=nullif(current_setting('request.headers',true),'')::jsonb->>'x-portal-club';
 if h is null or h='' then return '00000000-0000-4000-8000-000000000001'::uuid;end if;
 begin return h::uuid;exception when invalid_text_representation then return null;end;
end $$;
create or replace function public.current_app_role() returns text language sql stable security definer set search_path=public as $$
 select case when a.app_role='system_admin' then 'system_admin'
 when public.portal_club_admin(public.portal_current_club()) then 'admin'
 when exists(select 1 from public.portal_club_memberships m where m.person_id=a.person_id and m.club_id=public.portal_current_club() and m.active and m.role='member') then 'readonly'
 else 'portal_user' end from public.app_users a where a.user_id=auth.uid() and a.active
$$;
create function public.portal_club_data_allowed(c uuid) returns boolean language sql stable security definer set search_path=public as $$
 select c=public.portal_current_club() and (public.is_system_admin() or public.portal_club_member(c))
$$;
grant select,insert,update,delete on public.admin_notifications to authenticated;
revoke truncate,references,trigger on public.admin_notifications from authenticated,anon;
alter table public.admin_notifications add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.admin_notifications alter column club_id set default public.portal_current_club();
create index on public.admin_notifications(club_id);
create policy portal_club_boundary on public.admin_notifications as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.communication_history to authenticated;
revoke truncate,references,trigger on public.communication_history from authenticated,anon;
alter table public.communication_history add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.communication_history alter column club_id set default public.portal_current_club();
create index on public.communication_history(club_id);
create policy portal_club_boundary on public.communication_history as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.email_campaigns to authenticated;
revoke truncate,references,trigger on public.email_campaigns from authenticated,anon;
alter table public.email_campaigns add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.email_campaigns alter column club_id set default public.portal_current_club();
create index on public.email_campaigns(club_id);
create policy portal_club_boundary on public.email_campaigns as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.email_messages to authenticated;
revoke truncate,references,trigger on public.email_messages from authenticated,anon;
alter table public.email_messages add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.email_messages alter column club_id set default public.portal_current_club();
create index on public.email_messages(club_id);
create policy portal_club_boundary on public.email_messages as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.event_automation_rules to authenticated;
revoke truncate,references,trigger on public.event_automation_rules from authenticated,anon;
alter table public.event_automation_rules add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.event_automation_rules alter column club_id set default public.portal_current_club();
create index on public.event_automation_rules(club_id);
create policy portal_club_boundary on public.event_automation_rules as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.event_documents to authenticated;
revoke truncate,references,trigger on public.event_documents from authenticated,anon;
alter table public.event_documents add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.event_documents alter column club_id set default public.portal_current_club();
create index on public.event_documents(club_id);
create policy portal_club_boundary on public.event_documents as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.event_email_reply_tokens to authenticated;
revoke truncate,references,trigger on public.event_email_reply_tokens from authenticated,anon;
alter table public.event_email_reply_tokens add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.event_email_reply_tokens alter column club_id set default public.portal_current_club();
create index on public.event_email_reply_tokens(club_id);
create policy portal_club_boundary on public.event_email_reply_tokens as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.event_notes to authenticated;
revoke truncate,references,trigger on public.event_notes from authenticated,anon;
alter table public.event_notes add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.event_notes alter column club_id set default public.portal_current_club();
create index on public.event_notes(club_id);
create policy portal_club_boundary on public.event_notes as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.event_participants to authenticated;
revoke truncate,references,trigger on public.event_participants from authenticated,anon;
alter table public.event_participants add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.event_participants alter column club_id set default public.portal_current_club();
create index on public.event_participants(club_id);
create policy portal_club_boundary on public.event_participants as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.event_people to authenticated;
revoke truncate,references,trigger on public.event_people from authenticated,anon;
alter table public.event_people add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.event_people alter column club_id set default public.portal_current_club();
create index on public.event_people(club_id);
create policy portal_club_boundary on public.event_people as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.event_registration_answers to authenticated;
revoke truncate,references,trigger on public.event_registration_answers from authenticated,anon;
alter table public.event_registration_answers add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.event_registration_answers alter column club_id set default public.portal_current_club();
create index on public.event_registration_answers(club_id);
create policy portal_club_boundary on public.event_registration_answers as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.event_registration_fields to authenticated;
revoke truncate,references,trigger on public.event_registration_fields from authenticated,anon;
alter table public.event_registration_fields add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.event_registration_fields alter column club_id set default public.portal_current_club();
create index on public.event_registration_fields(club_id);
create policy portal_club_boundary on public.event_registration_fields as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.event_template_automations to authenticated;
revoke truncate,references,trigger on public.event_template_automations from authenticated,anon;
alter table public.event_template_automations add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.event_template_automations alter column club_id set default public.portal_current_club();
create index on public.event_template_automations(club_id);
create policy portal_club_boundary on public.event_template_automations as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.event_template_documents to authenticated;
revoke truncate,references,trigger on public.event_template_documents from authenticated,anon;
alter table public.event_template_documents add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.event_template_documents alter column club_id set default public.portal_current_club();
create index on public.event_template_documents(club_id);
create policy portal_club_boundary on public.event_template_documents as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.event_templates to authenticated;
revoke truncate,references,trigger on public.event_templates from authenticated,anon;
alter table public.event_templates add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.event_templates alter column club_id set default public.portal_current_club();
create index on public.event_templates(club_id);
create policy portal_club_boundary on public.event_templates as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.events to authenticated;
revoke truncate,references,trigger on public.events from authenticated,anon;
alter table public.events add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.events alter column club_id set default public.portal_current_club();
create index on public.events(club_id);
create policy portal_club_boundary on public.events as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.fiken_billing_run_items to authenticated;
revoke truncate,references,trigger on public.fiken_billing_run_items from authenticated,anon;
alter table public.fiken_billing_run_items add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.fiken_billing_run_items alter column club_id set default public.portal_current_club();
create index on public.fiken_billing_run_items(club_id);
create policy portal_club_boundary on public.fiken_billing_run_items as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id) and club_id='00000000-0000-4000-8000-000000000001'::uuid) with check(public.portal_club_data_allowed(club_id) and club_id='00000000-0000-4000-8000-000000000001'::uuid);
grant select,insert,update,delete on public.fiken_billing_runs to authenticated;
revoke truncate,references,trigger on public.fiken_billing_runs from authenticated,anon;
alter table public.fiken_billing_runs add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.fiken_billing_runs alter column club_id set default public.portal_current_club();
create index on public.fiken_billing_runs(club_id);
create policy portal_club_boundary on public.fiken_billing_runs as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id) and club_id='00000000-0000-4000-8000-000000000001'::uuid) with check(public.portal_club_data_allowed(club_id) and club_id='00000000-0000-4000-8000-000000000001'::uuid);
grant select,insert,update,delete on public.fiken_contacts to authenticated;
revoke truncate,references,trigger on public.fiken_contacts from authenticated,anon;
alter table public.fiken_contacts add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.fiken_contacts alter column club_id set default public.portal_current_club();
create index on public.fiken_contacts(club_id);
create policy portal_club_boundary on public.fiken_contacts as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id) and club_id='00000000-0000-4000-8000-000000000001'::uuid) with check(public.portal_club_data_allowed(club_id) and club_id='00000000-0000-4000-8000-000000000001'::uuid);
grant select,insert,update,delete on public.fiken_invoices to authenticated;
revoke truncate,references,trigger on public.fiken_invoices from authenticated,anon;
alter table public.fiken_invoices add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.fiken_invoices alter column club_id set default public.portal_current_club();
create index on public.fiken_invoices(club_id);
create policy portal_club_boundary on public.fiken_invoices as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id) and club_id='00000000-0000-4000-8000-000000000001'::uuid) with check(public.portal_club_data_allowed(club_id) and club_id='00000000-0000-4000-8000-000000000001'::uuid);
grant select,insert,update,delete on public.form_answers to authenticated;
revoke truncate,references,trigger on public.form_answers from authenticated,anon;
alter table public.form_answers add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.form_answers alter column club_id set default public.portal_current_club();
create index on public.form_answers(club_id);
create policy portal_club_boundary on public.form_answers as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.form_question_options to authenticated;
revoke truncate,references,trigger on public.form_question_options from authenticated,anon;
alter table public.form_question_options add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.form_question_options alter column club_id set default public.portal_current_club();
create index on public.form_question_options(club_id);
create policy portal_club_boundary on public.form_question_options as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.form_questions to authenticated;
revoke truncate,references,trigger on public.form_questions from authenticated,anon;
alter table public.form_questions add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.form_questions alter column club_id set default public.portal_current_club();
create index on public.form_questions(club_id);
create policy portal_club_boundary on public.form_questions as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.form_recipients to authenticated;
revoke truncate,references,trigger on public.form_recipients from authenticated,anon;
alter table public.form_recipients add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.form_recipients alter column club_id set default public.portal_current_club();
create index on public.form_recipients(club_id);
create policy portal_club_boundary on public.form_recipients as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.form_responses to authenticated;
revoke truncate,references,trigger on public.form_responses from authenticated,anon;
alter table public.form_responses add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.form_responses alter column club_id set default public.portal_current_club();
create index on public.form_responses(club_id);
create policy portal_club_boundary on public.form_responses as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.forms to authenticated;
revoke truncate,references,trigger on public.forms from authenticated,anon;
alter table public.forms add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.forms alter column club_id set default public.portal_current_club();
create index on public.forms(club_id);
create policy portal_club_boundary on public.forms as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.general_expenses to authenticated;
revoke truncate,references,trigger on public.general_expenses from authenticated,anon;
alter table public.general_expenses add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.general_expenses alter column club_id set default public.portal_current_club();
create index on public.general_expenses(club_id);
create policy portal_club_boundary on public.general_expenses as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.group_members to authenticated;
revoke truncate,references,trigger on public.group_members from authenticated,anon;
alter table public.group_members add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.group_members alter column club_id set default public.portal_current_club();
create index on public.group_members(club_id);
create policy portal_club_boundary on public.group_members as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.groups to authenticated;
revoke truncate,references,trigger on public.groups from authenticated,anon;
alter table public.groups add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.groups alter column club_id set default public.portal_current_club();
create index on public.groups(club_id);
create policy portal_club_boundary on public.groups as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.helper_entries to authenticated;
revoke truncate,references,trigger on public.helper_entries from authenticated,anon;
alter table public.helper_entries add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.helper_entries alter column club_id set default public.portal_current_club();
create index on public.helper_entries(club_id);
create policy portal_club_boundary on public.helper_entries as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.helper_expenses to authenticated;
revoke truncate,references,trigger on public.helper_expenses from authenticated,anon;
alter table public.helper_expenses add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.helper_expenses alter column club_id set default public.portal_current_club();
create index on public.helper_expenses(club_id);
create policy portal_club_boundary on public.helper_expenses as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.helper_rates to authenticated;
revoke truncate,references,trigger on public.helper_rates from authenticated,anon;
alter table public.helper_rates add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.helper_rates alter column club_id set default public.portal_current_club();
create index on public.helper_rates(club_id);
create policy portal_club_boundary on public.helper_rates as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.helper_requests to authenticated;
revoke truncate,references,trigger on public.helper_requests from authenticated,anon;
alter table public.helper_requests add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.helper_requests alter column club_id set default public.portal_current_club();
create index on public.helper_requests(club_id);
create policy portal_club_boundary on public.helper_requests as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.integration_sync_status to authenticated;
revoke truncate,references,trigger on public.integration_sync_status from authenticated,anon;
alter table public.integration_sync_status add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.integration_sync_status alter column club_id set default public.portal_current_club();
create index on public.integration_sync_status(club_id);
create policy portal_club_boundary on public.integration_sync_status as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id) and club_id='00000000-0000-4000-8000-000000000001'::uuid) with check(public.portal_club_data_allowed(club_id) and club_id='00000000-0000-4000-8000-000000000001'::uuid);
grant select,insert,update,delete on public.library_documents to authenticated;
revoke truncate,references,trigger on public.library_documents from authenticated,anon;
alter table public.library_documents add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.library_documents alter column club_id set default public.portal_current_club();
create index on public.library_documents(club_id);
grant select,insert,update,delete on public.library_folder_permissions to authenticated;
revoke truncate,references,trigger on public.library_folder_permissions from authenticated,anon;
alter table public.library_folder_permissions add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.library_folder_permissions alter column club_id set default public.portal_current_club();
create index on public.library_folder_permissions(club_id);
grant select,insert,update,delete on public.library_folders to authenticated;
revoke truncate,references,trigger on public.library_folders from authenticated,anon;
alter table public.library_folders add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.library_folders alter column club_id set default public.portal_current_club();
create index on public.library_folders(club_id);
grant select,insert,update,delete on public.person_roles to authenticated;
revoke truncate,references,trigger on public.person_roles from authenticated,anon;
alter table public.person_roles add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.person_roles alter column club_id set default public.portal_current_club();
create index on public.person_roles(club_id);
create policy portal_own_role_read on public.person_roles for select to authenticated using(person_id=public.current_person_id());
create policy portal_club_read_boundary on public.person_roles as restrictive for select to authenticated using(public.portal_club_data_allowed(club_id) or person_id=public.current_person_id());
create policy portal_club_insert_boundary on public.person_roles as restrictive for insert to authenticated with check(public.portal_club_data_allowed(club_id));
create policy portal_club_update_boundary on public.person_roles as restrictive for update to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
create policy portal_club_delete_boundary on public.person_roles as restrictive for delete to authenticated using(public.portal_club_data_allowed(club_id)) ;
grant select,insert,update,delete on public.roles to authenticated;
revoke truncate,references,trigger on public.roles from authenticated,anon;
alter table public.roles add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.roles alter column club_id set default public.portal_current_club();
create index on public.roles(club_id);
create policy portal_club_boundary on public.roles as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.sms_campaigns to authenticated;
revoke truncate,references,trigger on public.sms_campaigns from authenticated,anon;
alter table public.sms_campaigns add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.sms_campaigns alter column club_id set default public.portal_current_club();
create index on public.sms_campaigns(club_id);
create policy portal_club_boundary on public.sms_campaigns as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.sms_messages to authenticated;
revoke truncate,references,trigger on public.sms_messages from authenticated,anon;
alter table public.sms_messages add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.sms_messages alter column club_id set default public.portal_current_club();
create index on public.sms_messages(club_id);
create policy portal_club_boundary on public.sms_messages as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
grant select,insert,update,delete on public.sms_replies to authenticated;
revoke truncate,references,trigger on public.sms_replies from authenticated,anon;
alter table public.sms_replies add column club_id uuid not null default '00000000-0000-4000-8000-000000000001' references public.portal_clubs;
alter table public.sms_replies alter column club_id set default public.portal_current_club();
create index on public.sms_replies(club_id);
create policy portal_club_boundary on public.sms_replies as restrictive for all to authenticated using(public.portal_club_data_allowed(club_id)) with check(public.portal_club_data_allowed(club_id));
alter table public.roles drop constraint "roles_name_key";
alter table public.roles add constraint "roles_name_key" UNIQUE (club_id,name);
alter table public.groups drop constraint "groups_name_key";
alter table public.groups add constraint "groups_name_key" UNIQUE (club_id,name);
alter table public.helper_rates drop constraint "helper_rates_year_rate_type_key";
alter table public.helper_rates add constraint "helper_rates_year_rate_type_key" UNIQUE (club_id,year, rate_type);

-- Reports use the caller's row policies rather than bypassing them.
alter function public.admin_dashboard_data() security invoker;
alter function public.admin_helper_year_overview(integer) security invoker;
alter function public.my_portal_dashboard() security invoker;
revoke all on function public.portal_current_club(),public.portal_club_data_allowed(uuid) from public;
grant execute on function public.portal_current_club(),public.portal_club_data_allowed(uuid) to authenticated,service_role;
commit;
